# Generated by Django 5.1.7 on 2025-03-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deligate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(default='Male rep', max_length=100)),
                ('reg_no', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=500)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='votingapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('Y1S1', 'Year1Sem1'), ('Y1S2', 'Year1Sem2'), ('Y2S1', 'Year2Sem1'), ('Y2S2', 'Year2Sem2'), ('Y3S1', 'Year3Sem1'), ('Y3S2', 'Year3Sem2'), ('Y4S1', 'Year4Sem1'), ('Y4S2', 'Year4Sem2')], default='Year1Sem1', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingapp.department')),
            ],
        ),
    ]
