# Generated by Django 5.1.7 on 2025-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='stage',
            field=models.CharField(choices=[('Y1S1', 'Year1Sem1'), ('Y1S2', 'Year1Sem2'), ('Y2S1', 'Year2Sem1'), ('Y2S2', 'Year2Sem2'), ('Y3S1', 'Year3Sem1'), ('Y3S2', 'Year3Sem2'), ('Y4S1', 'Year4Sem1'), ('Y4S2', 'Year4Sem2')], max_length=20),
        ),
    ]
