# Generated by Django 5.1.4 on 2025-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0003_alter_deligate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deligate',
            name='position',
            field=models.CharField(choices=[('MR', 'Male representative'), ('FR', 'Female representative'), ('AR', 'Academic representative')], max_length=100),
        ),
    ]
