# Generated by Django 5.1.4 on 2025-03-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0006_alter_vote_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='deligate',
            name='vote',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
