# Generated by Django 5.1.4 on 2025-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0007_delete_vote_deligate_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('reg_no', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='deligate',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
