# Generated by Django 5.1.4 on 2025-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0010_remove_student_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
