# Generated by Django 5.1.4 on 2025-03-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0012_student_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
    ]
