# Generated by Django 5.1.4 on 2025-03-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0013_remove_student_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_admin',
        ),
    ]
